openapi: 3.1.1
info:
  title: OpenAPI to Django Example
  description: >-
    This is an example document for the [OpenAPI to
    Django](https://github.com/jaytik1/openapi_to_django) project, used to
    convert OpenAPI specifications into Django skeleton projects.
  license:
    name: MIT License
    url: https://opensource.org/license/mit
  version: 1.0.0
externalDocs:
  description: OpenAPI to Django GitHub repository
  url: https://github.com/jaytik1/openapi_to_django
servers:
  - url: https://example.com/
tags:
  - name: example
    description: Example endpoints
    externalDocs:
      description: Find out more
      url: http://example.com/
paths:
  /example/{id}:
    get:
      tags:
        - example
      summary: Get an example
      description: Get an example
      operationId: getExample
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          $ref: '#/components/responses/ExampleSuccess'
        '400':
          $ref: '#/components/responses/InvalidId'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - example_auth:
            - read:example
    head:
      tags:
        - example
      summary: Headers for getting a given example
      description: Headers for getting a given example
      operationId: headExample
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Headers for getting a given example
        '400':
          $ref: '#/components/responses/InvalidId'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - example_auth:
            - read:example
    put:
      tags:
        - example
      summary: Update a given example
      description: Update a given example
      operationId: updateExample
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        $ref: '#/components/requestBodies/ExampleRequest'
      responses:
        '200':
          $ref: '#/components/responses/ExampleSuccess'
        '400':
          $ref: '#/components/responses/InvalidId'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - example_auth:
            - write:example
    patch:
      tags:
        - example
      summary: Update part of a given example
      description: Update part of a given example
      operationId: patchExample
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        $ref: '#/components/requestBodies/ExampleRequest'
      responses:
        '200':
          $ref: '#/components/responses/ExampleSuccess'
        '400':
          $ref: '#/components/responses/InvalidId'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - example_auth:
            - write:example
    delete:
      tags:
        - example
      summary: Delete a given example
      description: Delete a given example
      operationId: deleteExample
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '204':
          description: Deleted example
        '400':
          $ref: '#/components/responses/InvalidId'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - example_auth:
            - write:example
  /example:
    post:
      tags:
        - example
      summary: Create a new example
      description: Create a new example
      operationId: createExample
      requestBody:
        $ref: '#/components/requestBodies/ExampleRequest'
      responses:
        '200':
          $ref: '#/components/responses/ExampleSuccess'
        '400':
          description: Invalid input
      security:
        - example_auth:
            - write:example
    options:
      tags:
        - example
      summary: Options for the example endpoint
      description: Options for the example endpoint
      operationId: optionsExample
      responses:
        '200':
          description: Options for the example endpoint
    trace:
      tags:
        - example
      summary: Trace the example endpoint
      description: Trace the example endpoint
      operationId: traceExample
      responses:
        '200':
          description: Trace the example endpoint
  /newExample:
    $ref: '#/components/pathItems/newExamplePath'
components:
  schemas:
    Example:
      required:
        - dateExample
        - integerExample
        - objectExample
      type: object
      properties:
        stringExample:
          type: string
          example: stringExample
        dateExample:
          type: string
          format: date
          example: '2025-01-10'
        booleanExample:
          type: boolean
          example: true
        numberExample:
          type: number
          format: float
          example: 5.6
        arrayExample:
          type: array
          items:
            type: string
            enum:
              - Monday
              - Wednesday
              - Friday
            example: Wednesday
            xml:
              name: Day
        objectExample:
          type: object
          properties:
            integerExample:
              type: integer
              format: int64
              example: 5
      xml:
        name: Example
  responses:
    ExampleSuccess:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Example'
        application/xml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Example'
    NewExampleSuccess:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Example'
        application/xml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Example'
      headers:
        Server:
          $ref: '#/components/headers/ExampleServerHeader'
    InvalidId:
      description: Invalid ID
    NotFound:
      description: Example not found
  parameters:
    Id:
      name: id
      in: path
      description: Example path parameter
      required: true
      schema:
        type: integer
      examples:
        Id49:
          summary: Example ID with value 49
          value: 49
        Id83:
          $ref: '#/components/examples/ExampleId83'
  examples:
    ExampleId83:
      summary: Example ID with value 83
      value: 83
  requestBodies:
    ExampleRequest:
      description: Example request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Example'
        application/xml:
          schema:
            $ref: '#/components/schemas/Example'
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/Example'
  headers:
    ExampleServerHeader:
      description: The server being used
      schema:
        type: string
        example: Example Server
  securitySchemes:
    example_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth/authorize
          scopes:
            write:example: Modify examples
            read:example: Read examples
  pathItems:
    newExamplePath:
      get:
        tags:
          - example
        summary: Get an example in a new way
        description: Get an example in a new way
        operationId: getNewExample
        responses:
          '200':
            $ref: '#/components/responses/NewExampleSuccess'
          '400':
            $ref: '#/components/responses/InvalidId'
          '404':
            $ref: '#/components/responses/NotFound'
