name: Python workflow

on: ["push"] # TODO remove this line, used for testing
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Type check with mypy
      run: mypy --cobertura-xml-report reports/ --junit-xml reports/mypy-junit.xml
    - name: Upload mypy Cobertura and JUnit reports
      uses: actions/upload-artifact@v1
      path: reports/
