name: Python workflow

on: push
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Check type hints with mypy
      run: |
        pip install mypy types-PyYAML
        mypy
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies with Poetry
      run: |
        pip install poetry
        poetry install
    - name: Perform unit tests with Pytest
      run: |
        poetry run pytest -v
